import nodemailer from 'nodemailer';

// Create transporter — supports Gmail (service) or any raw SMTP host.
// For Gmail: set SMTP_USER=youraddress@gmail.com, SMTP_PASS=your-app-password
// For Brevo/other: set SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASS
const createTransporter = () => {
  const host = process.env.SMTP_HOST || '';
  const isGmail =
    host.includes('gmail') ||
    (process.env.SMTP_USER || '').includes('@gmail.com');

  if (isGmail) {
    // Gmail: use the built-in service shorthand (handles TLS/port automatically)
    return nodemailer.createTransport({
      service: 'gmail',
      auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASS,
      },
    });
  }

  // Generic SMTP (Brevo, Mailgun, SendGrid, etc.)
  const port = parseInt(process.env.SMTP_PORT || '587');
  return nodemailer.createTransport({
    host,
    port,
    secure: port === 465, // auto-use SSL for port 465
    auth: {
      user: process.env.SMTP_USER,
      pass: process.env.SMTP_PASS,
    },
    tls: {
      rejectUnauthorized: false, // allow self-signed certs in dev
    },
  });
};

interface SendEmailOptions {
  to: string;
  subject: string;
  html: string;
  text?: string;
  attachments?: Array<{ filename: string; content: Buffer }>;
}

export async function sendEmail({ to, subject, html, text, attachments }: SendEmailOptions): Promise<boolean> {
  try {
    const transporter = createTransporter();

    const mailOptions = {
      from: `"NightPulse" <${process.env.SMTP_FROM || process.env.SMTP_USER}>`,
      to,
      subject,
      text: text || html.replace(/<[^>]*>/g, ''),
      html,
      attachments: attachments?.map(att => ({
        filename: att.filename,
        content: att.content,
        encoding: 'base64',
      })),
    };

    await transporter.sendMail(mailOptions);
    return true;
  } catch (error) {
    console.error('Email send error:', error);
    return false;
  }
}

interface InvoiceEmailOptions {
  to: string;
  clientName: string;
  invoiceNumber: string;
  totalAmount: number;
  dueDate: Date;
  clubName: string;
  isReceipt?: boolean;
  pdfAttachment?: {
    filename: string;
    content: Buffer;
  };
}

export async function sendPasswordResetEmail({
  to,
  clientName,
  resetLink,
}: {
  to: string;
  clientName: string;
  resetLink: string;
}) {
  const transporter = createTransporter();
  const mailOptions = {
    from: process.env.SMTP_FROM || `"NightPulse" <${process.env.SENDER_EMAIL}>`,
    to,
    subject: 'Password Reset Request - NightPulse',
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; color: #333;">
        <h2 style="color: #6366f1;">NightPulse Password Reset</h2>
        <p>Hello ${clientName},</p>
        <p>We received a request to reset your password. Click the button below to set a new password:</p>
        <div style="text-align: center; margin: 30px 0;">
          <a href="${resetLink}" style="background-color: #6366f1; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; font-weight: bold;">Reset Password</a>
        </div>
        <p>This link will expire in 1 hour. If you didn't request a password reset, you can safely ignore this email.</p>
        <hr style="border: none; border-top: 1px solid #eee; margin: 20px 0;" />
        <p style="font-size: 12px; color: #666;">Generated by NightPulse Auth System</p>
      </div>
    `,
  };

  try {
    const info = await transporter.sendMail(mailOptions);
    console.log('Password reset email sent: %s', info.messageId);
    return true;
  } catch (error) {
    console.error('Send password reset email error:', error);
    return false;
  }
}

export async function sendInvoiceEmail({
  to,
  clientName,
  invoiceNumber,
  totalAmount,
  dueDate,
  clubName,
  isReceipt = false,
  pdfAttachment,
}: InvoiceEmailOptions): Promise<boolean> {
  const subject = isReceipt
    ? `Receipt for Your Payment - ${invoiceNumber} | NightPulse`
    : `Invoice ${invoiceNumber} from ${clubName} | NightPulse`;

  const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>
    body { font-family: 'Helvetica Neue', Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px; }
    .header { background: linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%); color: white; padding: 30px; border-radius: 10px 10px 0 0; text-align: center; }
    .header h1 { margin: 0; font-size: 24px; }
    .content { background: #f9fafb; padding: 30px; border-radius: 0 0 10px 10px; }
    .greeting { font-size: 18px; margin-bottom: 20px; }
    .message { margin-bottom: 20px; }
    .details-box { background: white; border-radius: 8px; padding: 20px; margin: 20px 0; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
    .detail-row { display: flex; justify-content: space-between; padding: 10px 0; border-bottom: 1px solid #eee; }
    .detail-row:last-child { border-bottom: none; font-weight: bold; font-size: 18px; color: #6366f1; }
    .detail-label { color: #666; }
    .detail-value { font-weight: 600; }
    .cta-button { display: inline-block; background: #6366f1; color: white; padding: 12px 30px; text-decoration: none; border-radius: 6px; margin: 20px 0; font-weight: 600; }
    .footer { text-align: center; margin-top: 30px; padding-top: 20px; border-top: 1px solid #eee; color: #666; font-size: 14px; }
    .badge { display: inline-block; padding: 4px 12px; border-radius: 20px; font-size: 12px; font-weight: 600; }
    .badge-invoice { background: #fef3c7; color: #d97706; }
    .badge-receipt { background: #d1fae5; color: #059669; }
  </style>
</head>
<body>
  <div class="header">
    <h1>${isReceipt ? '🧾 Payment Receipt' : '📄 Invoice'}</h1>
    <p style="margin: 10px 0 0 0; opacity: 0.9;">${clubName}</p>
  </div>

  <div class="content">
    <p class="greeting">Dear ${clientName},</p>

    <p class="message">
      ${isReceipt
      ? `Thank you for your payment! Your receipt is attached below. We appreciate your business and look forward to serving you again.`
      : `You have received a new invoice from <strong>${clubName}</strong>. Please review the details below and make payment by the due date.`
    }
    </p>

    <div class="details-box">
      <div class="detail-row">
        <span class="detail-label">${isReceipt ? 'Receipt Number' : 'Invoice Number'}</span>
        <span class="detail-value">${invoiceNumber}</span>
      </div>
      <div class="detail-row">
        <span class="detail-label">Date</span>
        <span class="detail-value">${new Date().toLocaleDateString('en-KE')}</span>
      </div>
      ${!isReceipt ? `
      <div class="detail-row">
        <span class="detail-label">Due Date</span>
        <span class="detail-value">${dueDate.toLocaleDateString('en-KE')}</span>
      </div>
      ` : ''}
      <div class="detail-row">
        <span class="detail-label">Total ${isReceipt ? 'Paid' : 'Due'}</span>
        <span class="detail-value">KES ${totalAmount.toLocaleString()}</span>
      </div>
      <div class="detail-row">
        <span class="detail-label">Includes Service Tax (0.5%)</span>
        <span class="detail-value">Yes</span>
      </div>
    </div>

    <p style="text-align: center;">
      <span class="badge ${isReceipt ? 'badge-receipt' : 'badge-invoice'}">
        ${isReceipt ? 'PAID' : 'PENDING PAYMENT'}
      </span>
    </p>

    <p style="text-align: center; margin-top: 20px;">
      ${isReceipt
      ? 'Keep this receipt for your records.'
      : 'If you have any questions about this invoice, please contact the club directly.'
    }
    </p>

    <div class="footer">
      <p>Thank you for choosing ${clubName}!</p>
      <p style="margin-top: 10px;">
        <em>This is an automated message from NightPulse</em>
      </p>
    </div>
  </div>
</body>
</html>
  `;

  const attachments: Array<{ filename: string; content: Buffer }> = [];
  if (pdfAttachment) {
    attachments.push({
      filename: pdfAttachment.filename,
      content: pdfAttachment.content,
    });
  }

  return sendEmail({ to, subject, html, attachments });
}
